
spring:
  dubbo:
      application:
        name: provider
      base-package: com.fast.api
      registry:
        address: zookeeper://47.100.223.169
        port: 2181
      protocol:
        name: dubbo
        serialization: hessian2
      provider:
        retries: 0
  kafka:
    bootstrap-servers: 47.100.223.169:9092
    consumer:
      group-id: 0
server:
  port: 8080