
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://47.100.223.169:3306/goods-kill?useUnicode=true&characterEncoding=utf-8
    username: root
    password: Yuzj2018$

    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    filters: stat,wall,log4j
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    #建表时使用InnoDB引擎
    databasePlatform: "org.hibernate.dialect.MySQL5InnoDBDialect"

  dubbo:
      application:
        name: provider
      base-package: com.fast.api
      registry:
        address: zookeeper://47.100.223.169
        port: 2181
      protocol:
        name: dubbo
        serialization: hessian2
      provider:
        retries: 0
server:
  port: 8083